Feature/issue 11 & 4
nkte8/skyshare pull request #14
Opened 2024-02-27 13:28 UTC by nkte8

@ZEKE320 コードレビュをお願いします
（多分プロジェクトに参加していないのが原因でレビュワーに設定できなかった...もし今後も開発見ていきたい/Contributeしていきたいという話であれば、招待する方法調べます！）

resolve #11, resolve #4

2024-02-27 13:37 UTC, nkte8 commented on astro/src/components/Client/intents/PopupPreviewForm.tsx
> +import { getOgpMeta } from "../../../utils/getOgp"
（セルフレビュー）
ここダサい。`@/utils/getOgp`に直すこと。

2024-02-27 14:11 UTC, ZEKE320 commented
レビューの件了解しました。早速ローカルでチェックしますね！進捗があればまた共有します！

2024-02-27 14:18 UTC, ZEKE320 commented
平日はあまり時間がとれないかもしれませんが
もしよければ今後も手伝いますよ！

2024-02-27 15:17 UTC, nkte8 commented
@ZEKE320 ありがたい！私もあくまで趣味の延長でしかないので大きな活動は基本的に土日です。
プロジェクトへの追加方法（？）探しておきますね！

2024-02-27 16:11 UTC, ZEKE320 commented
@nkte8 ちょうど今入りました！ありがとうございます！

2024-02-27 16:30 UTC, nkte8 commented
レビュワーに追加しました！レビューのやり方はコードに[こんな感じ](https://github.com/nkte8/skyshare/pull/14#discussion_r1504244613)でコメントを入れたりします。File Changedのタブです。満足に入れ終わったら Commentか、Approve（承認）か、Change Request（要改修）かを出すって感じです！（使い方把握されてたら失礼しました！）

2024-02-27 19:38 UTC, ZEKE320 commented
ちなみにCloudflare WorkersとFirebaseのどちらにもあまり詳しくなくて…

本番環境より先にローカルで検証できれば良いと思っていますが、
Astro以外のサービスは普段どうやって環境構築してますか？

2024-02-27 19:48 UTC, ZEKE320 commented on astro/.env.local
おそらくローカル開発環境用という意味でファイル名`.env.local`となっているものと思うのですが、
正しくは`.env.development`な気がしています

# 以下読み飛ばして問題ないです

Astroでは`.env`ファイルを定義する際に`.env.production`や`.env.development`とすることで本番環境と開発環境のモード切替と同時に、使用される`.env`ファイルが切り替わるようです

今回`.env.local`には`localhost`や`192.168.x.x`のようなローカルネットワークの定義が含まれいるので、
開発環境用とみなして`.env.development`でも良いのかなと思っています

[環境変数|Astro Docs](https://docs.astro.build/ja/guides/environment-variables/#%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%99%E3%82%8B)

またViteのドキュメントで紹介されている通り、`.local`で終わる環境変数ファイルには非公開にしておきたい情報（APIのトークンなど）を含むことが多かったりします

[Env Variables and Modes|Vite](https://vitejs.dev/guide/env-and-mode.html#env-files)

ちなみにGitHubが公開している.gitignoreのテンプレートを導入しておくと、非公開にしておきたいファイルの多くをgitの追跡から除外してくれるので、いくらか安心して開発できるようになります

[gitignore/Node.gitignore](https://github.com/github/gitignore/blob/main/Node.gitignore)

2024-02-28 09:29 UTC, nkte8 commented
@ZEKE320 
> ちなみにCloudflare WorkersとFirebaseのどちらにもあまり詳しくなくて…
ローカルで検証する際に
Astro以外のサービスは普段どうやって環境構築していますか？

Readmeの説明がちょっと足りませんでしたねこれ。どっかで追記しておきます。

## firebase setup
firebase/README.md 
firebase-toolsをインストールして、nom run build（firebaseはtsを解釈できないので、jsにトランスパイル必要）、firebase serveでローカルに配信する感じ
```md
## Setup

install firebase develp tool

    npm install -g firebase-tools

## Build and Deploy

debug in local(extract to private network)

    npm run build
    firebase serve -o 192.168.3.200 -p 5000

```

## Cloudflare Worker setup
workers/README.md
こっちはインストール方法も書いてあった。確認してみて。wranglerについてはトランスパイル不要（cloudflare側で色々やってくれるっぽい）
```md
## Setup repository
install wrangler environment have X window system

    sudo npm install -g wrangler

setup repository

    npm install


## Build & Debug

local server build & debug

    kill -9 $(lsof -t -i:8087)
    wrangler --port 8087 dev 

```

2024-02-28 09:35 UTC, nkte8 commented on astro/.env.local
コメントありがとうございます！
ドキュメントには書いてないのですが、どうやらAstroで`npm run dev`を実行した場合は`.env.local`→`.env.development`→`.env`の順で読み込まれるみたいです。

ただ仰る通りこの部分って公式Doc書いておらず、コードを読む側としても分かりずらいのでファイル変えておきます。
これまではステージング環境に `.env.development`を使っていた（ので.gitignoreがこれを指していた）のですが、ステージング環境の変数は`.env.staging`とかで別途設定する変更を行いますね！

2024-02-28 09:49 UTC, nkte8 commented
↑結構言葉足らずだったので追記しました（hotfixでマージ済み）ご確認ください。

Firebase: https://github.com/nkte8/skyshare/blob/main/firebase/README.md  
Cloudflare worker: https://github.com/nkte8/skyshare/blob/main/workers/README.md

2024-02-28 10:11 UTC, nkte8 commented
ローカルで建てるにしてもこれあれですね。Upstash産のデータベースがないと開発が難しい、またはこの箇所を実行しているコードをスキップするようにしてあげないといけないので、不親切ですね...
うーん...どうするべきなんだろう。mockを立てれれば一番いいのですが、そこらへんの知見がなく...

2024-02-28 10:59 UTC, ZEKE320 commented
なるほどなるほど！

2024-02-28 11:10 UTC, ZEKE320 commented on astro/.env.local
@nkte8 
なるほどそういう経緯でしたか
すみません、対応ありがとうございます

2024-02-28 11:55 UTC, ZEKE320 commented on astro/.env.local
@nkte8 あ、コミットしてもらった`.env.dev`なんですが、Astroから見えていないみたいですね...
とりあえず`.env.development`にリネームしてからは動作しているので、一旦こちらで検証してみますね

2024-02-28 12:15 UTC, ZEKE320 commented on astro/src/utils/envs.ts
> +export const siteurl = () => {
現状`siteurl`が関数として定義されていますが、
```ts
const stagingSiteUrl = String(import.meta.env.PUBLIC_STAGING_SITE_URL)
export const siteurl = (typeof stagingSiteUrl!== "undefined" && stagingSiteUrl !== "") ? stagingSiteUrl : import.meta.env.SITE;
```
のように定数で置き換えてみてはどうでしょう？

2024-02-28 12:16 UTC, ZEKE320 commented on astro/src/utils/envs.ts
> +export const siteurl = () => {
あ、すごい見づらいですね
直します

2024-02-28 12:16 UTC, ZEKE320 commented on astro/src/utils/envs.ts
> +}
現状`siteurl`が関数として定義されていますが、
```ts
const stagingSiteUrl = String(import.meta.env.PUBLIC_STAGING_SITE_URL)
export const siteurl = (typeof stagingSiteUrl!== "undefined" && stagingSiteUrl !== "") ? stagingSiteUrl : import.meta.env.SITE;
```
のように定数で置き換えてみてはどうでしょう？

2024-02-28 13:29 UTC, ZEKE320 commented
@nkte8 
> ローカルで建てるにしてもこれあれですね。Upstash産のデータベースがないと開発が難しい、またはこの箇所を実行しているコードをスキップするようにしてあげないといけないので、不親切ですね...
うーん...どうするべきなんだろう。mockを立てれれば一番いいのですが、そこらへんの知見がなく...

了解です
とりあえずfetch()が適当に置き換えてレビューを進めますね！

2024-02-28 13:42 UTC, ZEKE320 commented
本当に文字通りWorkersもFirebaseもほとんど扱ったことがないので
バックエンドの処理は土日の時間があるときにまた確認しておきます

2024-02-28 14:01 UTC, ZEKE320 commented
@nkte8 
Blueskyでも送りましたが招待メールを送る形式なら
hw3pcj8dh@mozmail.com
に送ってもらえれば

2024-02-28 14:28 UTC, nkte8 commented
@ZEKE320 だ、大問題です…そんなばかな…githubのログインは消したのでもうメール認証だけになってると思います、いかがでしょう…？

2024-02-28 14:44 UTC, ZEKE320 commented
@nkte8 
ダミーで用意した意味があまり無いような笑
ダミーメールで再度認証しました！

GitHub側のOAuthは割と早い段階でrevokeしておきましたが、
メールアドレスくらい何とかなるので大丈夫です

2024-02-28 16:25 UTC, ZEKE320 commented on astro/.env.local
@nkte8 こちらの件、一回レビュー内容を整理してから再掲しますね。一旦Resolveします。

2024-02-28 16:26 UTC, ZEKE320 commented on astro/src/utils/envs.ts
> +}
@nkte8 こちらもまた後日まとめて再掲します

2024-02-28 16:39 UTC, ZEKE320 commented on astro/.env.dev
> +PUBLIC_STAGING_SITE_URL="http://192.168.3.200:4321"
@nkte8
この行はAstroのAPIサーバーを意味するURLということで間違いないですか？

2024-02-28 16:43 UTC, nkte8 commented on astro/.env.dev
> +PUBLIC_STAGING_SITE_URL="http://192.168.3.200:4321"
はい。このアドレスってCORSヘッダと併用で設定しちゃってるので運用的に微妙そう。
なのでCORSとは切り離そうと思います。（後、レビューコメントはこれで終わりの認識であってます？まとめて出してくれた結果これだけだと思っていますが...）

2024-02-28 16:46 UTC, ZEKE320 commented
@nkte8
すみません。つづきがありまして。
Firebaseが～、Cloudflare Workersが～など訳の分からないことを言ってしまって申し訳ないです。
恐らくそこが勘違いしていたところで、基本的に今回のレビューでAstro以外は必要ないかもしれないですね。
せっかく準備していただいたのですが開発環境はレビューとは分けて触った方が良いかもしれません。

2024-02-28 16:50 UTC, ZEKE320 commented
@nkte8 
今回のレビューの範囲がastroフォルダ内の変更範囲のみという事であれば、
まず期限として今週の土曜日19時ごろに設定させていただいても良いでしょうか？

レビュー内容をすべてまとめてからとはいえ、
期限が決まっていないのは精神衛生上よろしくないことと、
平日はあまり時間がとれないためです。

おそらくその程度時間があれば検証は十分できるかと思いますし、
何より検証環境での動作確認より前に一度レビュー後の問題点の解消を行うべきだと考えているからです。

2024-02-28 17:06 UTC, nkte8 reviewed
これは4箇所一気にレビューを出す例です

2024-02-28 17:06 UTC, nkte8 commented on astro/src/utils/getOgp.ts
> +        return await response.json()
よく見ると暗黙的な型変換が行われている。（fetchの返し型はPromise<any>なのに、関数はPromise<ogpMataData | errorResponse>となっている）どうにかなるならどうにかしたい。

2024-02-28 17:11 UTC, nkte8 commented
> 今回のレビューの範囲がastroフォルダ内の変更範囲のみという事であれば、
まず期限として今週の土曜日19時ごろに設定させていただいても良いでしょうか？

はい大丈夫です！（レビューなんてちょっと大袈裟に言ってしまいましたが、厳密に設計を決めているわけではないので、体感的に普通はこのように書く〜みたいなところが知れたらいいな、と思っていました！すくなくともtypescriptの開発経験がZEKEさんの方が豊富なように見えたので...）

> おそらくその程度時間があれば検証は十分できるかと思いますし、
何より検証環境での動作確認より前に一度レビューや対話による問題点の解消を行うべきであると考えています。
現状検証環境もうまく動作していないようなので。

Ah...検証環境（ステージング？）死んでますか...多分セルフレビューで挙げた CORSの部分ですかね....すみません、これ先に直してとりあえず動くようにだけしてあげた方がいいかな...？

2024-02-28 18:24 UTC, nkte8 commented
@ZEKE320 とりあえずステージング環境で動くところにまでは持っていっておいたので、必要に応じて https://feature-issue-11.skyshare.pages.dev/app/ で試してみてください。コード（特に環境変数について）も少し見直しました。ご確認いただければと思います。（うまく意思疎通できず、往復多くなってしまってすみません...）

(以下動作証跡)
<img width="567" alt="screenshot" src="https://github.com/nkte8/skyshare/assets/91360587/7fe6c8f3-4563-4f61-83fe-0169d89b2fe1">

2024-02-28 18:26 UTC, nkte8 commented on astro/src/utils/envs.ts
> +}
そもそもサイトのURLを環境変数に持たせる設計がダメだったため、修正済み

2024-02-28 18:26 UTC, nkte8 commented on astro/src/pages/api/getOgpBlob.ts
> +        "Access-Control-Allow-Origin": siteurl(),
切り出し処理、完了。

2024-02-28 18:26 UTC, nkte8 commented on astro/src/pages/api/getOgpMeta.ts
> +        "Access-Control-Allow-Origin": siteurl(),
切り出し済み

2024-02-28 18:28 UTC, nkte8 commented on astro/src/utils/getOgp.ts
> +        return await response.json()
あまり良くない書き方かも知れない（他の方法を知らない...）が、一応対処済み
```
        if (!response?.ok) {
            let res: errorResponse = await response.json()
            let e: Error = new Error(res.message)
            e.name = res.error
            throw e
        }
        return await response.json() as ogpMataData
```

2024-02-29 00:39 UTC, ZEKE320 commented on astro/.env.dev
> +PUBLIC_STAGING_SITE_URL="http://192.168.3.200:4321"
すみません。
`192.168.x.x`の形式だったので、外部に何らかのサーバーを用意しなければならないものと勘違いしていました。
開発環境ではひとまず環境変数のIPを`localhost`や`127.0.0.1`に置き換えて検証すればよいということですね

2024-02-29 03:41 UTC, ZEKE320 commented
@nkte8 
ステージング環境、ローカル環境の両方で検証可能になりました
対応ありがとうございます。

また昨日の件ですが、急ぎ気味で書いてしまったこともあり
まとまりに欠ける文になっていたかと思います。すみません。

改めて要点は次のとおりです
1. 余裕をもってレビューを行いたいので、3/2(土) 19時頃に一度レビュー内容を投稿します
2. 現状FirebaseとCloudflare Workersの環境がローカルで再現できていないため、今回はこれらの機能がサーバー上で期待通り動くものと仮定します
3. ステージング環境にソースマップの情報が含まれていないようなので、こちらはデバッグ用ではなく、レビュー対応後のシステムテスト（と言えるものか分かりませんが）で用います

またPRで直接連絡を行っていたことも問題だったかと思います
本来であればSlackなどでGitHubとは分離して連絡をしつつ
PRやIssueを汚さないような対応が一般的ですが、
今回その点で配慮が足りていなかったと反省しています

GitHubのディスカッションを有効にしていただければ
今後はそちらで質問や連絡等は行いますがどうでしょうか

2024-02-29 03:56 UTC, nkte8 commented
@ZEKE320 承知です！
disscussion #21 を作ったので、細かな質問などはそっちでやりましょう。こちらこそいろいろやりずらい感じになってしまってすみませんでした。

2024-03-02 05:46 UTC, nkte8 commented
[開発者ルール](https://github.com/nkte8/skyshare/wiki/Developer-Reference-%7C-開発者リファレンス) を制定しましたが、本ブランチの作成後になってしまったので、 https://feature-issue-11.skyshare.pages.dev/ に限っては従来通り開けるようにしています。

2024-03-02 10:00 UTC, ZEKE320 requested changes
レビュー完了しました。
確認をお願いします。

2024-03-02 15:43 UTC, nkte8 commented on astro/src/components/Client/pagedb/PageViewForm.tsx
> +const siteurl = location.origin
見落としです！発見ありがとうございます！

2024-03-02 15:43 UTC, nkte8 commented on astro/src/components/Client/intents/PopupPreviewForm.tsx
> +                const ogp = await getOgpMeta(siteurl, popupContent.url.toString())
あーたしかに...改善項目としましょう。
Issueに該当のテンプレートがないので別のcommitで作っておきます。

2024-03-02 15:44 UTC, nkte8 commented on astro/src/utils/recordBuilder.ts
>          let embed: embed.external = {
Object型って中の値を変える分には定数でも変更できるんですね..初めて知りました。ありがとうございます。

2024-03-02 15:44 UTC, nkte8 commented on astro/src/lib/types.ts
> +export type ogpMataData = {
おー...ちゃんと公式でコード規約あるんですね、とてもいいと思います。多分広範囲にわたる変更が必要になると思うので、本PRでは一旦無視させてください。
綴り間違いの発見感謝です！こちらは修正します。

2024-03-02 15:44 UTC, nkte8 commented on astro/src/utils/getOgp.ts
> +            e.name = `${res.error}@getOgpMeta`
ありがとうございます！間違えてました...

2024-03-02 15:47 UTC, nkte8 commented
@ZEKE320 詳細なレビューをありがとうございます！Typescript歴短いゆえ、非常に助かります。
指摘箇所については一旦修正を実施しました！お忙しいところ恐縮ですが、よろしければ再確認していただければ幸いです🙇

2024-03-02 16:12 UTC, nkte8 commented
(直す前にマージすればよかった...Confrict的にもそっちのがらくだろうし...)

2024-03-02 16:30 UTC, nkte8 commented on astro/src/components/Client/intents/PopupPreviewForm.tsx
> +                const ogp = await getOgpMeta(siteurl, popupContent.url.toString())
Issue https://github.com/nkte8/skyshare/issues/28 に別途切りました！

2024-03-03 05:49 UTC, ZEKE320 commented
@nkte8 
対応ありがとうございます！
確認中なので少々お待ちを...

2024-03-03 07:57 UTC, ZEKE320 commented on astro/src/lib/validateRequest.ts
> +    if (url.toLowerCase().search(/(http|https):\/\/localhost/) > 0) {
この件、色々考える必要がありそうなので、
別PRで対応しておきますね

2024-03-03 11:03 UTC, ZEKE320 commented
@nkte8 
再レビュー完了しました
レビュー範囲の変更については問題ないかと思いますが、
Twitter投稿のプレビュー画面の挙動が怪しい気がしているので一度動作検証しますね！

2024-03-03 11:47 UTC, ZEKE320 requested changes
今のところ検証で問題が起きているのはXの投稿プレビューのみなので、
一度レビューで返してしまいますね。

2024-03-03 11:47 UTC, ZEKE320 commented on astro/src/components/Client/intents/PopupPreviewForm.tsx
>                                  ogpUrl !== null && (
@nkte8 
OGPが設定されていないサイトの共有時に
Twitter側の投稿プレビューが正しく動作していないようでした。
次のコードで直ります
```diff
<>
  {
+   ogpUrl !== null && ogpUrl !== "" && (
      {/*画像用*/}
      ...
    ) 
  }
  {
+   ogpMeta !== null && ogpMeta.title !== "" && (
      {/*タイトル用*/}
      ...
    )
  }
<>
```

2024-03-03 16:01 UTC, ZEKE320 commented
@nkte8 
そのほかのコードで特別気になった点は無いので、

- SSRF対策 PR #30
- 上記のX投稿プレビュー問題

が解決次第、こちらへ確認なしでマージ・実機検証に進んでしまって問題ありません


また今後の開発方針ですが、基本的にはこちらのレビューは無しで良いかと考えています
（というのもSkyshare自体の理解度も開発頻度もねこのさんの方が高いので...）

こちらで実装した箇所については前回同様PRを作成します

どうしても気になる点があれば、必要に応じてDiscussion, Issue, PRから連絡するような形式でどうでしょうか？
もちろん「念のためセカンドオピニオンが必要」といった状況であれば、遠慮なくレビューを投げてもらって構いません！

2024-03-04 15:03 UTC, nkte8 commented on astro/src/components/Client/intents/PopupPreviewForm.tsx
>                                  ogpUrl !== null && (
検証・コード案の提示ありがとうございます！！
ありがとうございます、これ見落としでした。ついでなのでOGP画像が設定されていないページ向けにダミーを表示するようにしました。
```ts
{
    ogpUrl !== null && ogpUrl !== "" ? (
        <img src={ogpUrl} className="w-full rounded-3xl aspect-video object-cover border-2" />
    ) : (
        <div className="w-full rounded-3xl py-10 object-cover border-2 text-gray-300">
            No OGP image found at {popupContent.url.host.toString()}
        </div>
    )
}
{
    ogpMeta !== null && ogpMeta.title !== "" && (
        <div className="absolute bottom-2 left-4 bg-opacity-70 rounded-md px-2 text-white bg-black">
            {ogpMeta.title}
        </div>
    )
}
```

2024-03-04 15:09 UTC, nkte8 commented
@ZEKE320 
> どうしても気になる点があれば、必要に応じてDiscussion, Issue, PRから連絡するような形式でどうでしょうか？
もちろん「念のためセカンドオピニオンが必要」といった状況であれば、遠慮なくレビューを投げてもらって構いません！

これで行きましょう！いきなりレビュアー振ってしまってすみません、忙しい可能性もあったのに浅はかでした....

振り回してしまいましたがご協力、ほんｔっとうにありがとうございました！！非常に良いコードになったと思います。謝辞はこれからdevelopにマージして CHANGELOG編集する際に書かせていただきます....

2024-03-04 15:18 UTC, merged